<a href="https://colab.research.google.com/github/tejaswinimaddireddy678-web/Data-science-/blob/main/groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#groupby enables categorywise analysis instead of row by row analysis

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/drive/MyDrive/datascience files/weather_by_cities.csv")

In [ ]:
df

In [ ]:
#find maximum temperature in each of cities
#find average wind speed per city

In [11]:
g=df.groupby("city")

In [ ]:
for city,city_df in g:
  print(city)
  print(city_df)

In [16]:
g.get_group("mumbai")

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [17]:
df.columns

Index(['day', 'city', 'temperature', 'windspeed', 'event'], dtype='object')

In [18]:
df.groupby("city")['temperature'].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [19]:
#find average wind speed per city
df.groupby("city")["windspeed"].mean()

city
mumbai       9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

In [21]:
#find the total wind speed for each city
df.groupby("city")["windspeed"].sum()

city
mumbai      37
new york    32
paris       51
Name: windspeed, dtype: int64

In [22]:
#find the highest wind speed for each city
df.groupby("city")["windspeed"].max()

city
mumbai      15
new york    12
paris       20
Name: windspeed, dtype: int64